-- MySQL Script generated by MySQL Workbench
-- Mon Jan 30 02:48:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `checkpoint4`.`artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checkpoint4`.`artist` ;

CREATE TABLE IF NOT EXISTS `checkpoint4`.`artist` (
  `id_artist` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_artist`),
  UNIQUE INDEX `id_artist_UNIQUE` (`id_artist` ASC) VISIBLE)
ENGINE = InnoDB;

INSERT INTO
  `checkpoint4`.`artist` ( name, image_url )
VALUES
  ( 'Metallica', 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Metallica_logo.png' ),
  ( 'The Beatles', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/The_Beatles_logo.svg/1200px-The_Beatles_logo.svg.png' ),
  ( 'Michael Jackson', 'https://1000logos.net/wp-content/uploads/2020/10/Michael-Jackson-Logo.png' );

-- -----------------------------------------------------
-- Table `checkpoint4`.`album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checkpoint4`.`album` ;

CREATE TABLE IF NOT EXISTS `checkpoint4`.`album` (
  `id_album` INT NOT NULL AUTO_INCREMENT,
  `title_album` VARCHAR(255) NOT NULL,
  `genre` VARCHAR(255) NOT NULL,
  `picture` VARCHAR(255) NOT NULL,
  `fk_id_artist` INT NOT NULL,
  PRIMARY KEY (`id_album`),
  UNIQUE INDEX `id_album_UNIQUE` (`id_album` ASC) VISIBLE,
  INDEX `fk_id_artist_idx` (`fk_id_artist` ASC) VISIBLE,
  CONSTRAINT `fk_id_artist`
    FOREIGN KEY (`fk_id_artist`)
    REFERENCES `checkpoint4`.`artist` (`id_artist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO
  `checkpoint4`.`album` (title_album, genre, picture, fk_id_artist )
VALUES
  ( 'The Black Album', 'Heavymetal' ,'https://i.ytimg.com/vi/DqDeH3hwxfw/maxresdefault.jpg', 1),
  ( 'Reload', 'Heavymetal' ,'https://townsquare.media/site/366/files/2016/11/Metallica-Reload-Anniversary.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89', 1),
  ( 'Revolver', 'Rock','https://cdn.shopify.com/s/files/1/0548/6424/8961/products/RS218_1LPvinyl_DigitalStereocover_Revolver-SpecialEdition_be7b3902-cc0a-40e6-bb00-8682a987ebd2_grande.jpg?v=1663066173', 2),
  ( 'Bad', 'Pop', 'https://upload.wikimedia.org/wikipedia/en/5/51/Michael_Jackson_-_Bad.png', 3 );


-- -----------------------------------------------------
-- Table `checkpoint4`.`track`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checkpoint4`.`track` ;

CREATE TABLE IF NOT EXISTS `checkpoint4`.`track` (
  `id_track` INT NOT NULL AUTO_INCREMENT,
  `title_track` VARCHAR(128) NOT NULL,
  `youtube_url` VARCHAR(255) NOT NULL,
  `fk_id_album` INT NOT NULL,
  PRIMARY KEY (`id_track`),
  UNIQUE INDEX `id_track_UNIQUE` (`id_track` ASC) VISIBLE,
  INDEX `fk_id_album_idx` (`fk_id_album` ASC) VISIBLE,
  CONSTRAINT `fk_id_album`
    FOREIGN KEY (`fk_id_album`)
    REFERENCES `checkpoint4`.`album` (`id_album`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO
  `checkpoint4`.`track` (title_track, youtube_url, fk_id_album )
VALUES
  ( 'Enter Sandman', 'https://www.youtube.com/watch?v=CD-E-LDc384', 1),
  ( 'Sad but True', 'https://www.youtube.com/watch?v=A8MO7fkZc5o', 1),
  ( 'Holier than Thou', 'https://www.youtube.com/watch?v=Jk8magGDcKE', 1),
  ( 'The Unforgiven', 'https://www.youtube.com/watch?v=Ckom3gf57Yw', 1),
  ( 'Wherever I May Roam', 'https://www.youtube.com/watch?v=Z-cEyiM9adE', 1),
  ( 'Dont Tread on Me', 'https://www.youtube.com/watch?v=fh-TKJTCtnw', 1),
  ( 'Through the Never', 'https://www.youtube.com/watch?v=Cdru3Z_F_Sw', 1),
  ( 'Nothing Else Matters', 'https://www.youtube.com/watch?v=tAGnKpE4NCI', 1),
  ( 'Of Wolf and Man', 'https://www.youtube.com/watch?v=-3la4-WWCcE', 1),
  ( 'The God That Failed', 'https://www.youtube.com/watch?v=Or8Ba20Q_OY', 1),
  ( 'My Friend of Misery', 'https://www.youtube.com/watch?v=ODHhWcEdrvg', 1),
  ( 'The Struggle Within', 'https://www.youtube.com/watch?v=2HBfAKXsxZU', 1),
  ( 'Fuel', 'https://www.youtube.com/watch?v=PvF9PAxe5Ng', 2),
  ( 'The Memory Remains', 'https://www.youtube.com/watch?v=RDN4awrpPQQ', 2),
  ( 'Devils Dance', 'https://www.youtube.com/watch?v=R1-177SVHcM', 2),
  ( 'The Unforgiven II', 'https://www.youtube.com/watch?v=5bt7kAVxKfs', 2),
  ( 'Better than You', 'https://www.youtube.com/watch?v=FIYwZ8VsKqM', 2),
  ( 'Slither', 'https://www.youtube.com/watch?v=dBZYjlRb8vI', 2),
  ( 'Carpe Diem Baby', 'https://www.youtube.com/watch?v=tb6CnztUvDk', 2),
  ( 'Bad Seed', 'https://www.youtube.com/watch?v=tRweadugRy8', 2),
  ( 'Where the Wild Things Are', 'https://www.youtube.com/watch?v=rj7gU5n4J2I', 2),
  ( 'Prince Charming', 'https://www.youtube.com/watch?v=c5Ke2C639KU', 2),
  ( 'Low Mans Lyric', 'https://www.youtube.com/watch?v=vHl5d5Z2zWM', 2),
  ( 'Attitude', 'https://www.youtube.com/watch?v=YSNqJ2zxJ3A', 2),
  ( 'Fixxxer', 'https://www.youtube.com/watch?v=kF7U1zlletc', 2),
  ( 'Taxman', 'https://www.youtube.com/watch?v=gMdcE8jdz70', 3),
  ( 'Eleanor Rigby', 'https://www.youtube.com/watch?v=HuS5NuXRb5Y', 3),
  ( 'Im Only Sleeping', 'https://www.youtube.com/watch?v=5XwXliCK19Y', 3),
  ( 'Love You To', 'https://www.youtube.com/watch?v=iCs9goFpiQ0', 3),
  ( 'Here, There and Everywhere', 'https://www.youtube.com/watch?v=FusIKjztap8', 3),
  ( 'Yellow Submarine', 'https://www.youtube.com/watch?v=m2uTFF_3MaA', 3),
  ( 'She Said She Said', 'https://www.youtube.com/watch?v=NZOBWYHgZjw', 3),
  ( 'Good Day Sunshine', 'https://www.youtube.com/watch?v=R9ncBUcInTM', 3),
  ( 'And Your Bird Can Sing', 'https://www.youtube.com/watch?v=9g2eU9YGwWQ', 3),
  ( 'For No One', 'https://www.youtube.com/watch?v=hgJ7dmr_ysU', 3),
  ( 'Doctor Robert', 'https://www.youtube.com/watch?v=a396v8kuViw', 3),
  ( 'I Want to Tell You', 'https://www.youtube.com/watch?v=ja7P5890yIM', 3),
  ( 'Got to Get You into My Life', 'https://www.youtube.com/watch?v=rHwf0-yIemk', 3),
  ( 'Tomorrow Never Knows', 'https://www.youtube.com/watch?v=m4BuziKGMy4', 3),
  ( 'Bad', 'https://www.youtube.com/watch?v=Sd4SJVsTulc', 4),
  ( 'The Way You Make Me Feel', 'https://www.youtube.com/watch?v=HzZ_urpj4As', 4),
  ( 'Speed Demon', 'https://www.youtube.com/watch?v=l039y9FaIjc', 4),
  ( 'Liberian Girl', 'https://www.youtube.com/watch?v=70VrvkfjJjg', 4),
  ( 'Just Good Friends', 'https://www.youtube.com/watch?v=kt27N-_3Hjs', 4),
  ( 'Another Part of Me', 'https://www.youtube.com/watch?v=8vwHQNQ88cM', 4),
  ( 'Man in the Mirror', 'https://www.youtube.com/watch?v=PivWY9wn5ps', 4),
  ( 'I Just Cant Stop Loving You', 'https://www.youtube.com/watch?v=fKBiYBWRYDM', 4),
  ( 'Dirty Diana', 'https://www.youtube.com/watch?v=yUi_S6YWjZw', 4),
  ( 'Smooth Criminal', 'https://www.youtube.com/watch?v=h_D3VFfhvs4', 4),
  ( 'Leave Me Alone', 'https://www.youtube.com/watch?v=crbFmpezO4A', 4);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
